version: "3.9"

services:
  invoice_webapp:
    build: .
    container_name: invoice_webapp
    restart: always
    ports:
      - "5001:5000"  
    networks:
      - webnet      

networks:
  webnet:
    external: true
